# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: [ '10.x' ]
        os: [windows-2022, macos-14]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: dotnet restore 
        run: dotnet restore 
      - name: dotnet build 
        run: dotnet build --configuration Release --no-restore 
      - name: dotnet test 
        run: dotnet test --no-restore --verbosity normal 
      - name: Publish LocalMultiplayerAgent (Windows)
        if: matrix.os == 'windows-2022'
        run: dotnet publish LocalMultiplayerAgent --runtime win-x64 -c Release -o LocalMultiplayerAgentPublishFolder-win -p:PublishSingleFile=true --self-contained true
      - name: Publish LocalMultiplayerAgent (MacOS ARM)
        if: matrix.os == 'macos-14'
        run: dotnet publish LocalMultiplayerAgent --runtime osx-arm64 -c Release -o LocalMultiplayerAgentPublishFolder-macos -p:PublishSingleFile=true --self-contained true
      - name: Upload Windows artifact
        if: matrix.os == 'windows-2022'
        uses: actions/upload-artifact@v4
        with:
          name: LocalMultiplayerAgent-win-x64
          path: LocalMultiplayerAgentPublishFolder-win
      - name: Upload MacOS artifact
        if: matrix.os == 'macos-14'
        uses: actions/upload-artifact@v4
        with:
          name: LocalMultiplayerAgent-osx-arm64
          path: LocalMultiplayerAgentPublishFolder-macos
     
